; I2C Test Firmware — ESP32 DevKit
; SDA = GPIO21 (D21), SCL = GPIO22 (D22)
; Sensores: HTU21 (0x40), AHT20 (0x38), OLED SSD1306 (0x3C)

[env:esp32-devkit]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 460800

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM=0

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.10
    adafruit/Adafruit HTU21DF Library@^1.0.5
    adafruit/Adafruit AHTX0@^2.0.5
    adafruit/Adafruit BusIO@^1.16.1
