[env:gateway-esp32-enc28j60]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 460800

build_src_filter = +<*.cpp> +<*.h>
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -I../shared

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    https://github.com/Networking-for-Arduino/EthernetENC.git
    knolleary/PubSubClient @ ^2.8
